name: Editor Config format check

permissions: { }

on:
  workflow_call:
    secrets:
      envGH:
        required: true

jobs:
  validate:
    name: Validate Editor Config formatting
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
    - name: Checkout PR head branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Editor Config Validation against PR base commit
      uses: super-linter/super-linter/slim@12150456a73e248bdc94d0794898f94e23127c88 # v7.4.0
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_EDITORCONFIG: true
        DEFAULT_BRANCH: ${{ github.event.pull_request.base.sha }}
        GITHUB_TOKEN: ${{ secrets.envGH }}
        VALIDATE_MARKDOWN: true
