name: License Header Check

on:
  workflow_call:
    secrets:
      envGH:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check License Header
        uses: apache/skywalking-eyes@5c5b974209f0de5d905f37deb69369068ebfc15c # v0.7.0
        env:
            GITHUB_TOKEN: ${{ secrets.envGH }}  # needed only when you want License-Eye to comment on the pull request.
