name: JavaDoc Check

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #Build with java 21
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 #v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -Pjavadoc-check -B package --file pom.xml
