name: JavaDoc Check

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #Build with java 21
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b #v4.6.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -Pjavadoc-check -B package --file pom.xml
