name: Close stale issues and PRs

on:
  workflow_call:
    secrets:
      envGH:
        required: true

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          stale-issue-message: 'This issue has been marked stale due to lack of activity. Remove the stale label or make a comment to keep this issue open, or it will be closed automatically.'
          stale-pr-message: 'This pr has been marked stale due to lack of activity. Remove the stale label, make a comment or push a commit to keep this issue open, or it will be closed automatically.'
          days-before-stale: 60
          days-before-close: 5
          repo-token: ${{ secrets.envGH }}
