name: Deploy Maven

on:
  workflow_call:

jobs:
  publish:
    if: ${{ startsWith(github.repository, 'eclipse-osgi-technology/') && (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.ORG_GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Java for publishing to Maven Central Snapshot Repository
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: PASSPHRASE
      - name: deploy
        run: mvn -Pdeploy --no-transfer-progress --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.ORG_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
          PASSPHRASE: ${{ secrets.ORG_GPG_PASSPHRASE }}

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        continue-on-error: true
        uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3 # v4.0.3
        with:
          directory: '/'
