name: License Header Check

on:
  workflow_call:
    secrets:
      envGH:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check License Header
        uses: apache/skywalking-eyes@cd7b195c51fd3d6ad52afceb760719ddc6b3ee91 # v0.6.0
        env:
            GITHUB_TOKEN: ${{ secrets.envGH }}  # needed only when you want License-Eye to comment on the pull request.
