name: JavaDoc Check

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #Build with java 21
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #v4.7.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -Pjavadoc-check -B package --file pom.xml
