name: Eclipse-Dash IP-Check

on:
  workflow_call:
    secrets:
      GITLAB_API_TOKEN:
        required: false

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@adb6a1048802d77454d39365394ee74987778a25
    with:
      projectId: technology.osgi-technology
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}
